DATABASE_OF_EXTENSIONS = {'images': ['jpg',
                                     'bmp',
                                     'jpeg',
                                     'webp',
                                     'gif',
                                     'png',
                                     'img',
                                     ],
                          'documents': ['doc',
                                        'docx',
                                        'odt',
                                        'rtf',
                                        'xls',
                                        'xlsx',
                                        'txt',
                                        'ods',
                                        'pdf',
                                        ],
                          'audio': ['mp3',
                                    'wav',
                                    'flac',
                                    'ogg',
                                    'aac',
                                    ],
                          'video': ['mp4',
                                    'wmv',
                                    'flv',
                                    'ogv',
                                    'webm',
                                    'avi',
                                    'mpeg',
                                    ],
                          'archives': ['bztar',
                                       'gztar',
                                       'tar',
                                       'xztar',
                                       'zip',
                                       ]}
